#!/bin/sh
echo "Sourcing .rc"
START_SCRIPTS=~/startup-scripts
# Util, env and path goes even first!
source "$START_SCRIPTS"/util.sh
include "$START_SCRIPTS"/path.sh
include "$START_SCRIPTS"/env.sh
# Util, env and path always goes first

include "$START_SCRIPTS"/alias.sh
include "$START_SCRIPTS"/python.sh
include "$START_SCRIPTS"/kubernetes.sh
include "$START_SCRIPTS"/docker.sh
include "$START_SCRIPTS"/git.sh
if is_bash; then
    include "$START_SCRIPTS"/bash_prompt.sh
elif is_zsh; then
    include "$START_SCRIPTS"/zsh_prompt.sh
fi
include "$START_SCRIPTS"/title.sh
include "$START_SCRIPTS"/history.sh
include "$START_SCRIPTS"/openai.sh
. "$HOME/.cargo/env"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
