#!/bin/bash
echo "Sourcing .bashrc"
START_SCRIPTS=~/startup-scripts
# Util, env and path goes even first!
source "$START_SCRIPTS"/util.sh
include "$START_SCRIPTS"/env.sh
include "$START_SCRIPTS"/path.sh
# Util, env and path always goes first

include "$START_SCRIPTS"/alias.sh
include "$START_SCRIPTS"/python.sh
include "$START_SCRIPTS"/kubernetes.sh
include "$START_SCRIPTS"/docker.sh
include "$START_SCRIPTS"/home.sh
include "$START_SCRIPTS"/git.sh
include "$START_SCRIPTS"/prompt.sh
include "$START_SCRIPTS"/title.sh
include "$START_SCRIPTS"/history.sh
include "$START_SCRIPTS"/completion.sh
include "$START_SCRIPTS"/fzf.sh
