tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# Programmable completion for Bash 3.2
brew "bash-completion"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# General-purpose data compression with high compression ratio
brew "xz"
# Interpreted, interactive, object-oriented programming language
brew "python@3.9"
# Core application library for C
brew "glib"
# Cross-platform make
brew "cmake"
# Color-highlighted diff(1) output
brew "colordiff"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Reimplementation of ctags(1)
brew "ctags"
# Load/unload environment variables based on $PWD
brew "direnv"
# Pack, ship and run any application as a lightweight container
brew "docker"
# Isolated development environments using Docker
brew "docker-compose"
# Create Docker hosts locally and on cloud providers
brew "docker-machine"
# CLI tool for quick access to files and directories
brew "fasd"
# Identify or delete duplicate files
brew "fdupes"
# GNU multiple precision arithmetic library
brew "gmp"
# GNU Ubiquitous Intelligent Language for Extensions
brew "guile"
# GNU Transport Layer Security (TLS) Library
brew "gnutls"
# Generate introspection data for GObject libraries
brew "gobject-introspection"
# OpenType text shaping engine
brew "harfbuzz"
# NaCl networking and cryptography library
brew "libsodium"
# Collection of GNU find, xargs, and locate
brew "findutils"
# Command-line fuzzy finder written in Go
brew "fzf"
# Graphics library to dynamically manipulate images
brew "gd"
# Access GitHub's .gitignore boilerplates
brew "gibo"
# Distributed revision control system
brew "git"
# Git extension for versioning large files
brew "git-lfs"
# Framework for layout and rendering of i18n text
brew "pango"
# User-friendly cURL replacement (command-line HTTP client)
brew "httpie"
# Add GitHub support to git on the command-line
brew "hub"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Utility for directing compilation
brew "make"
# Python version management
brew "pyenv"
# Readline wrapper: adds readline support to tools that lack it
brew "rlwrap"
# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"
# Code-search similar to ack
brew "the_silver_searcher"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Tool for creating isolated virtual python environments
brew "virtualenv", link: false
# Python virtualenv extensions
brew "virtualenvwrapper", link: false
# Internet file retriever
brew "wget"
# Tracks most-used directories to make cd smarter
brew "z"
# General-purpose lossless data-compression library
brew "zlib"
# Application launcher and productivity software
cask "alfred"
cask "day-o"
# Web browser
cask "firefox"
cask "font-fira-code"
# Set of tools to manage resources and applications hosted on Google Cloud
cask "google-cloud-sdk"
# Client for the Google Drive storage service
cask "google-drive"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# Free and open-source OpenVPN client
cask "tunnelblick"
# Open-source code editor
cask "visual-studio-code"


